---
core:
  # server_url: https://<SPACE>.kinops.io  OR https://<SERVER_NAME>.com/kinetic/<SPACE_SLUG>
  server_url: https://web-server.com
  space_slug: <SPACE_SLUG>
  space_name: <SPACE_NAME>
  service_user_username: <USER_NAME>
  service_user_password: <PASSWORD>
options:
  EXPORT:
    space:
      models: # List of Models
        -  #model_name
      webapis:
          -  #webapi_slug
      space_workflows: # List of Form Workflows. {workflow event (e.g., 'Submission Submitted') OR name of workflow} (For version 6+ only)
        - #workflow_event
        - #workflow_name
      teams:
        # List Team Names
        # Use "include_membership: true" to export the team membership
        - team_name: #team_name
          include_membership: #{true:false}
      attributes:
        space: # List of Space Attributes
          -  #space_attribute
        user: # List of User Attributes
          -  #user_attribute
        user_profile: # List of User Profile Attributes
          -  #user_profile_attribute
        team: # List of Team Attributes
          -  #team_attribute
      
    kapps: # List Kapp Slugs
      # For "datastore" logic will determine if form consolidation is used by looking for the "datastore" kapp
      - kapp_slug: services #kapp_slug
        forms: # list form slugs
          - form_slug:  # form_slug to export
            form_definition:  # Export form definition {true:false}
            submissions:  # Export submissions {true:false}
            form_workflows: # List of Form Workflows. {workflow event (e.g., 'Submission Submitted') OR name of workflow} (For version 6+ only)
              - #workflow_event
              - #workflow_name 
        webapis:
          - #webapi_slug
        kapp_workflows: # List of Kapp Workflows. {workflow event (e.g., 'Submission Submitted') OR name of workflow} (For version 6+ only)
          - #workflow_event
          - #workflow_name
        attributes:
          kapp_attributes: # Kapp Attributes
            -  #kapp_attribute
          category_attributes: # Category Attributes
            -  #category_attribute
          form_attributes: # Form Attributes
            -  #form_attribute
        categories: # Category Slugs
          -  #category_slug
        securitypolicy:
          -  #name
    workflow:
      trees: #List of Trees
        # list each using - 'Source :: Source Group :: Name'
        # example: - 'Kinetic Request CE :: Submissions > services > gravel-roads :: Closed'
        -  #'Source :: Source Group :: Name'
      routines: #List of Routines
        # list each using - 'Source :: Source Group :: Name'
        # example: - '- :: - :: Name'
        -  #- :: - :: Name
      handlers: #List of Handlers
        -  #Handler_Definition_Id
  REMOVE_DATA_PROPERTIES: # Properties to remove from exported submissions
    - createdAt
    - createdBy
    - updatedAt
    - updatedBy
    - closedAt
    - closedBy
    - submittedAt
    - submittedBy
    - id
    - authStrategy
    - key
    - handle
task:
  # server_url: https://<SPACE>.kinops.io/app/components/task   OR https://<SERVER_NAME>.com/kinetic-task
  server_url: https://web-server.com
  service_user_username: <USER_NAME>
  service_user_password: <PASSWORD>
http_options:
  log_level: info
  log_output: stderr
